<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Document</title>
</head>
<body>
<form method="post" action="/transfer">
    <input type="text" placeholder="from" name="from">
    <input type="text" placeholder="to" name="to">
    <input type="number" placeholder="amount" name="amount">
    <input type="submit">
</form>
</body>
</html>